config/routes.rb
Victoria::Application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
resources :portfolio, :controller => :portfolios, :only => [:index, :show], :as => :portfolios
match 'about' => 'about#index', :as => :about
match 'contact' => 'about#contact', :as => :contact
match 'biography' => 'about#index'
match 'bio' => 'about#index'

resources :admin, :only => :index

 namespace :admin do
   resources :photos
   resources :photos_api do
     collection do
       put 'update'
     end
   end
   resources :clients
   resources :clients_api do
     collection do
       put 'update'
     end
   end
 end

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name, :sequence, :url
end

app/controllers/admin/clients_controller.rb
module Admin

  class ClientsController < ApplicationController
    before_filter :doAdminAuthentication
    private
    def doAdminAuthentication
      :authenticate_user!

      unless !current_user.nil? && current_user.owner
        not_found
      end
    end
    public
    def index
      @clients = Client.all :order => [:sequence, :name]
    end
    def show
      @client = Client.find params[:id]
    end
    def edit
      @client = Client.find params[:id]
    end
    def new
      @client = Client.new
    end
    def create
      client = Client.new().update_attributes(params[:client]  )

          unless client.nil?
            redirect_to :action => :index
          else
            render :create
          end
    end
    def update
      client = Client.find params[:id]
      client.update_attributes(params[:client])

      unless client.nil?
        redirect_to :action => :index
      else
        render :show
      end
    end

    def destroy
      Client.destroy(params[:id])
      redirect_to :action => :index
    end
  end
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/views/admin/clients/edit.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="featured-area">
<p><%= link_to "Back to List", admin_clients_path %>  </p>
<br />

<%= form_for [:admin, @client] do |f| %>


    <%= label_tag(:name, "Client name:") %>
    <%= f.text_field :name, 'required' => '' %>
    <br />

      <%= label_tag(:url, "Client url:") %>
      <%= f.text_field :url %>
      <br />

      <%= label_tag(:sequence, "Sequence:") %>
      <%= f.number_field :sequence %>
      <br />
    <%= submit_tag("Update") %>
<% end %>

      <div class="text-column">

        <p><%= link_to "Perma Delete", admin_client_path(@photo), :method => :delete, :class => 'btn btn-danger' %></p>
        </div>
      </div>
      </div>
    </div>

app/views/admin/clients/index.html.erb
<p><%= link_to "Back to List", admin_clients_path %>  </p>
<br/>
<%= javascript_include_tag "widgets/adminclient" %>

<p><%= link_to 'add new client', new_admin_client_path %> </p>
<table  class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Order</th>
      <th>Link</th>
      <th></th>
    </tr>
  </thead>
  <tbody data-bind="foreach: clients">
    <tr>
      <td class="client-section">
        <p data-bind="text:name, visible: !editMode()"></p>
        <input type="number" data-bind="value: saveClient().name, visible: editMode()" />
      </td>
      <td class="client-sequence">
        <p data-bind="text:sequence, visible: !editMode()"></p>
        <input type="number" data-bind="value: saveClient().sequence, visible: editMode()" />
      </td>
      <td class="client-url">
        <p data-bind="text:url, visible: !editMode()"></p>
        <input type="text" data-bind="value: saveClient().url, visible: editMode()" />
      </td>
      
      <td class="client-buttons">
        <button class="btn" data-bind="css:{'btn-inverse': !editMode(), 'btn-warning': editMode()}, text:editMode()? 'Cancel' : 'Edit', click: setEdit, enable: !isSaving()"></button>
        <button class="btn btn-success" data-bind="text:'Save', click: save, visible: editMode(), enable: !isSaving()"></button>

      </td>
    </tr>
  </tbody>
</table>
<p class="text-info" data-bind="visible: isLoading()">Loading, be right with you.</p>

app/views/admin/clients/new.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="featured-area">
<p><%= link_to "Back to List", admin_clients_path %>  </p>

      <%= form_for [:admin, @client] do |f| %>


          <%= label_tag(:name, "Client name:") %>
          <%= f.text_field :name, 'required' => '' %>
          <br />

          <%= label_tag(:url, "Client url:") %>
          <%= f.text_field :url %>
          <br />

          <%= label_tag(:sequence, "Sequence:") %>
          <%= f.number_field :sequence %>
          <br />
          <%= submit_tag("Save") %>
      <% end %>
      </div>
    </div>
</div>

app/views/admin/clients/show.html.erb
<p><%= link_to "Back to List", admin_clients_path %>  </p>
<br />
<p>Name: <%= @client.title %></p>
<p>Url: <%= @client.url %></p>
<p>Sequence: <%= @client.sequence %></p>
<p><%= link_to "Edit", edit_admin_client_path(@client) %></p>