config/routes.rb
Victoria::Application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
resources :portfolio, :controller => :portfolios, :only => [:index, :show], :as => :portfolios
match 'about' => 'about#index', :as => :about
match 'contact' => 'about#contact', :as => :contact
match 'biography' => 'about#index'
match 'bio' => 'about#index'

resources :admin, :only => :index

 namespace :admin do
   resources :photos
   resources :photos_api do
     collection do
       put 'update'
     end
   end
   resources :clients
   resources :clients_api do
     collection do
       put 'update'
     end
   end
 end

  root :to => 'home#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  before_destroy :before_destroy
  attr_accessible :description, :sequence, :title, :url, :picture, :visible, :horizontal, :portfolio
  def before_destroy
  options = {:account_name => ENV['AZURE_ACCOUNT_NAME'],
             :access_key => ENV['AZURE_ACCOUNT_PRIMARY_ACCESS_KEY']}
  WAZ::Storage::Base.establish_connection(options) do
    my_container = WAZ::Blobs::Container.find(ENV['AZURE_CONTAINER'])

    filename = PortfolioHelper::Utilities.new.getFileName(self.url)
    photoAzure = my_container[filename]
    unless photoAzure.nil?
      photoAzure.destroy!
    end
  end
end
end

app/controllers/admin/photos_controller.rb
require "waz-blobs"
require 'uri'

module Admin

   class PhotosController < ApplicationController
     before_filter :doAdminAuthentication
     private
     def doAdminAuthentication
       :authenticate_user!

       unless !current_user.nil? && current_user.owner
         not_found
       end
     end
    public
     def index
        @photos = Photo.all :order => [:portfolio, :sequence]
     end
     def show
       @photo = Photo.find params[:id]
     end
     def edit
       @photo = Photo.find params[:id]
     end
     def new
        @photo = Photo.new
     end
     def create
       uploaded_io = params[:photo][:picture]

       options = {:account_name => ENV['AZURE_ACCOUNT_NAME'],
                  :access_key => ENV['AZURE_ACCOUNT_PRIMARY_ACCESS_KEY']}
       WAZ::Storage::Base.establish_connection(options) do
         my_container = WAZ::Blobs::Container.find(ENV['AZURE_CONTAINER'])
         if my_container.nil?
           my_container = WAZ::Blobs::Container.create(ENV['AZURE_CONTAINER'])

         end
         new_photo_blob = my_container.store(uploaded_io.original_filename, uploaded_io.read, uploaded_io.content_type)
         if !new_photo_blob.nil? && !new_photo_blob.url.blank?
           new_photo = Photo.new(title:params[:photo][:title],
                                 description:params[:photo][:description],
                                 url:new_photo_blob.url,
                                 visible: params[:photo][:visible],
                                 sequence: params[:photo][:sequence],
                                 portfolio: params[:photo][:portfolio],
                                 horizontal: false)
           if new_photo.save
             redirect_to :action => :index
           else
             render :show
           end
         end
       end
     end
     def update
       @photo = Photo.find(params[:id])
       if !params[:photo].nil? && !params[:photo][:picture].nil?
         uploaded_io = params[:photo][:picture]
         if !uploaded_io.nil?
           uriPath = URI(@photo.url).path
           imageFileName = File.basename(uriPath)
           options = {:account_name => ENV['AZURE_ACCOUNT_NAME'],
                      :access_key => ENV['AZURE_ACCOUNT_PRIMARY_ACCESS_KEY']}
           WAZ::Storage::Base.establish_connection(options) do
             my_container = WAZ::Blobs::Container.find(ENV['AZURE_CONTAINER'])
             if my_container.nil?
               my_container = WAZ::Blobs::Container.create(ENV['AZURE_CONTAINER'])
             end
             new_photo_blob = my_container.store(imageFileName, uploaded_io.read, uploaded_io.content_type)
             @photo.url = new_photo_blob.url
           end
         end
       end
       @photo.save
       redirect_to :action => :index

     end
     def destroy
       Photo.destroy(params[:id])
       redirect_to :action => :index
     end
   end
end

app/views/admin/photos/edit.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="featured-area">
<p><%= link_to "Back to List", admin_photos_path %>  </p>
<br />

<%= form_for [:admin, @photo], :html => { :enctype => "multipart/form-data"} do |f| %>


    <%= label_tag(:picture, "Update image:") %>
    <%= f.file_field :picture, 'required' => '' %>
    <br />
    <%= submit_tag("Update") %>
<% end %>

      <div class="text-column">
<%= image_tag @photo.url, :alt => @photo.title %>

        <p><%= link_to "Perma Delete", admin_photo_path(@photo), :method => :delete, :class => 'btn btn-danger' %></p>
        </div>
      </div>
      </div>
    </div>

app/views/admin/photos/index.html.erb
<p><%= link_to "Back to List", admin_photos_path %>  </p>
<br/>
<%= javascript_include_tag "widgets/adminphoto" %>

<p><%= link_to 'upload new image', new_admin_photo_path %> </p>
<table  class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Section</th>
      <th>Order</th>
      <th>Image Name</th>
      <th>Link</th>
      <th>Visible</th>
      <th>Horizontal</th>
      <th></th>
    </tr>
  </thead>
  <tbody data-bind="foreach: photos">
    <tr>
      <td class="photo-section">
        <p data-bind="text:section, visible: !editMode()"></p>
        <select data-bind="options: $root.portfolios, value: savePhoto().section, visible: editMode()"></select>
      </td>
      <td class="photo-sequence">
        <p data-bind="text:sequence, visible: !editMode()"></p>
        <input type="number" data-bind="value: savePhoto().sequence, visible: editMode()" />
      </td>
      <td class="photo-title">
        <p data-bind="text:title, visible: !editMode()"></p>
        <input type="text" data-bind="value: savePhoto().title, visible: editMode()" />
      </td>
      <td class="photo-url">
        <p data-bind="text:url, visible: !editMode()"></p>
        <input type="text" data-bind="value: savePhoto().url, visible: editMode()" />
      </td>
      <td class="photo-visible">
        <p data-bind="text:visible, visible: !editMode()"></p>
        <select data-bind="options: $root.checks, optionsText: 'text', optionsValue: 'value', value: savePhoto().visible, visible: editMode()"></select>
      </td>
      <td class="photo-horizontal">
        <p data-bind="text:horizontal, visible: !editMode()"></p>
        <select data-bind="options: $root.checks, optionsText: 'text', optionsValue: 'value', value: savePhoto().horizontal, visible: editMode()"></select>
      </td>
      <td class="photo-buttons">
        <button class="btn" data-bind="css:{'btn-inverse': !editMode(), 'btn-warning': editMode()}, text:editMode()? 'Cancel' : 'Edit', click: setEdit, enable: !isSaving()"></button>
        <button class="btn btn-success" data-bind="text:'Save', click: save, visible: editMode(), enable: !isSaving()"></button>

        <p><a data-bind="attr: {href: '/admin/photos/' + id() + '/edit'}">edit photo</a></p>
      </td>
    </tr>
  </tbody>
</table>
<p class="text-info" data-bind="visible: isLoading()">Loading, be right with you.</p>

app/views/admin/photos/new.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="featured-area">
<p><%= link_to "Back to List", admin_photos_path %>  </p>

<%= form_for [:admin, @photo] do |f| %>

    <%= label_tag(:title, "Short title:") %>
    <%= f.text_field :title, 'required' => '' %>
          <br />
    <%= label_tag(:portfolio, "Portfolio:") %>
    <%= f.select :portfolio, %w[food interiors published] %>
          <br />
    <%= label_tag(:sequence, "Order of the image on the page:") %>
    <%= f.number_field :sequence, {:min=> 0, :step => 1} %>
          <br />
    <%= label_tag(:visible, "Should the image be shown:", :class=> "inline") %>
    <%= f.check_box :visible %>
          <br />
          <br />
    <%= label_tag(:horizontal, "Is the image horizontal:", :class=> "inline") %>
    <%= f.check_box :horizontal %>
          <br />
          <br />
    <%= label_tag(:picture, "Select an image:") %>
    <%= f.file_field :picture, 'required' => '' %>
          <br />
          <br />
    <%= submit_tag("Upload Image") %>
<% end %>
      </div>
    </div>
</div>

app/views/admin/photos/show.html.erb
<p><%= link_to "Back to List", admin_photos_path %>  </p>
<br />
<p>Title: <%= @photo.title %></p>
<p>Url: <%= @photo.url %></p>
<p>Portfolio: <%= @photo.portfolio %></p>
<p>Visible: <%= @photo.visible %></p>
<p>Description:<%= @photo.description %> </p>
<p><%= link_to "Edit", edit_admin_photo_path(@photo) %></p>
<br />
<%= image_tag @photo.url, :alt => @photo.title %>