config/routes.rb
Victoria::Application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
resources :portfolio, :controller => :portfolios, :only => [:index, :show], :as => :portfolios
match 'about' => 'about#index', :as => :about
match 'contact' => 'about#contact', :as => :contact
match 'biography' => 'about#index'
match 'bio' => 'about#index'

resources :admin, :only => :index

 namespace :admin do
   resources :photos
   resources :photos_api do
     collection do
       put 'update'
     end
   end
   resources :clients
   resources :clients_api do
     collection do
       put 'update'
     end
   end
 end

  root :to => 'home#index'

end

app/views/shared/_clientlist.html.erb
<div class="portfolio-text">
<h4>Clients include:</h4>

  <ul>
    <% (0..18).each do |x|
    unless (clients[x].blank?)
    %>

                  <li>
                    <%= clients[x].name %>
                  </li>
        <% end
           end %>

        </ul>
    </div>

app/views/shared/_footer.html.erb
<footer>


    <div class="side"></div>
  <div class="central">
      <div class="row-fluid">
        <div class="span12">
      <h4>&#169; Victoria Harley <%= Date.today.year.to_s %> - All rights reserved</h4>
        </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="notifications" xmlns="http://www.w3.org/1999/html">
  <% unless notice.nil? %>
      <p class="notice"><%= notice %></p>
  <% end %>
  <% unless alert.nil? %>
      <p class="alert"><%= alert %></p>
  <% end %>
</div>
<header>


    <div class="side"></div>
  <div class="central">
      <div class="row-fluid">
        <div class="span12">
      <h1><%= link_to "Victoria Harley Photography", root_path %> </h1>
        </div>
    </div>
  </div>
</header>

app/views/shared/_menu.html.erb
<nav>
  <ul>
    <li><%= link_to 'portfolio', portfolios_path %> </li>
    <li><%= link_to 'bio {about}', about_path %> </li>
    <li><%= link_to 'contact', contact_path %> </li>
    <li><%= link_to 'blog', 'http://split-pin.blogspot.co.uk' %> </li>
    <% if user_signed_in? %>
        <li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    <% end %>
  </ul>
</nav>